// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Game } from '../../../game/content-types/game/game';
import { TeamProfile } from '../../../team-profile/content-types/team-profile/team-profile';
import { Game_Plain } from '../../../game/content-types/game/game';
import { TeamProfile_Plain } from '../../../team-profile/content-types/team-profile/team-profile';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Team {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    image?: { data: Media };
    game?: { data: Game };
    name: string;
    team_profiles: { data: TeamProfile[] };
  };
}
export interface Team_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image?: Media;
  game?: Game_Plain;
  name: string;
  team_profiles: TeamProfile_Plain[];
}

export interface Team_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image?: number;
  game?: number;
  name: string;
  team_profiles: number[];
}

export interface Team_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image?: AdminPanelRelationPropertyModification<Media>;
  game?: AdminPanelRelationPropertyModification<Game_Plain>;
  name: string;
  team_profiles: AdminPanelRelationPropertyModification<TeamProfile_Plain>;
}
