// Interface automatically generated by schemas-to-ts

import { Profile } from '../../../profile/content-types/profile/profile';
import { Team } from '../../../team/content-types/team/team';
import { Profile_Plain } from '../../../profile/content-types/profile/profile';
import { Team_Plain } from '../../../team/content-types/team/team';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Role {
  Founder = 'founder',
  Member = 'member',
  Leader = 'leader',}

export interface TeamProfile {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    is_pending: boolean;
    role: Role;
    profile?: { data: Profile };
    team?: { data: Team };
    invited_by?: { data: Profile };
  };
}
export interface TeamProfile_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_pending: boolean;
  role: Role;
  profile?: Profile_Plain;
  team?: Team_Plain;
  invited_by?: Profile_Plain;
}

export interface TeamProfile_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_pending: boolean;
  role: Role;
  profile?: number;
  team?: number;
  invited_by?: number;
}

export interface TeamProfile_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_pending: boolean;
  role: Role;
  profile?: AdminPanelRelationPropertyModification<Profile_Plain>;
  team?: AdminPanelRelationPropertyModification<Team_Plain>;
  invited_by?: AdminPanelRelationPropertyModification<Profile_Plain>;
}
