// Interface automatically generated by schemas-to-ts

import { Profile } from '../../../profile/content-types/profile/profile';
import { Profile_Plain } from '../../../profile/content-types/profile/profile';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Deposit = 'deposit',
  Withdraw = 'withdraw',
  In = 'in',
  Out = 'out',}

export interface Transaction {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    confirmed: boolean;
    type: Type;
    amount: number;
    profile?: { data: Profile };
    txHash?: string;
    txBlockNumber?: number;
    allowanceTxBlockNumber?: number;
    onChainSinceBlockNumber?: number;
  };
}
export interface Transaction_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  confirmed: boolean;
  type: Type;
  amount: number;
  profile?: Profile_Plain;
  txHash?: string;
  txBlockNumber?: number;
  allowanceTxBlockNumber?: number;
  onChainSinceBlockNumber?: number;
}

export interface Transaction_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  confirmed: boolean;
  type: Type;
  amount: number;
  profile?: number;
  txHash?: string;
  txBlockNumber?: number;
  allowanceTxBlockNumber?: number;
  onChainSinceBlockNumber?: number;
}

export interface Transaction_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  confirmed: boolean;
  type: Type;
  amount: number;
  profile?: AdminPanelRelationPropertyModification<Profile_Plain>;
  txHash?: string;
  txBlockNumber?: number;
  allowanceTxBlockNumber?: number;
  onChainSinceBlockNumber?: number;
}
