// Interface automatically generated by schemas-to-ts

import { Game } from '../../../game/content-types/game/game';
import { Game_Plain } from '../../../game/content-types/game/game';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface GameMode {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    game?: { data: Game };
    title: string;
  };
}
export interface GameMode_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  game?: Game_Plain;
  title: string;
}

export interface GameMode_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  game?: number;
  title: string;
}

export interface GameMode_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  game?: AdminPanelRelationPropertyModification<Game_Plain>;
  title: string;
}
