// Interface automatically generated by schemas-to-ts

import { Profile } from '../../../profile/content-types/profile/profile';
import { Team } from '../../../team/content-types/team/team';
import { Profile_Plain } from '../../../profile/content-types/profile/profile';
import { Team_Plain } from '../../../team/content-types/team/team';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  TeamInviteReceived = 'TEAM_INVITE_RECEIVED',
  TransactionResult = 'TRANSACTION_RESULT',}

export interface Notification {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    type: Type;
    profile?: { data: Profile };
    team?: { data: Team };
    seen: boolean;
    transaction_result_details?: any;
  };
}
export interface Notification_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  type: Type;
  profile?: Profile_Plain;
  team?: Team_Plain;
  seen: boolean;
  transaction_result_details?: any;
}

export interface Notification_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  type: Type;
  profile?: number;
  team?: number;
  seen: boolean;
  transaction_result_details?: any;
}

export interface Notification_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  type: Type;
  profile?: AdminPanelRelationPropertyModification<Profile_Plain>;
  team?: AdminPanelRelationPropertyModification<Team_Plain>;
  seen: boolean;
  transaction_result_details?: any;
}
